language: node_js
node_js:
- "10.13"

env:
- SLS_DEBUG=* TWITTER_SCREEN_NAME=this_vid EXTERNAL_URL=thisvid.space TWITTER_CALLBACK_URL=http://thisvid.space/_/completetwittersignin

cache:
  directories:
  - node_modules

install: npm i && npm i -g serverless

stages:
- name: test
- name: lint
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: deploy
    script: sls deploy

  - stage: test
    script: npm run test

  - stage: lint
    script: npm run lint