name: Checks

on:
  push:
    branches: [master]
  pull_request:

env:
  NODE_ENV: development
  TWITTER_SCREEN_NAME: this_vid
  EXTERNAL_URL: thisvid.space

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests (Node.js 14.18.0)
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.0
      - run: npm i
      - name: Tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    name: Lint (Node.js 14.18.0)
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.0
      - run: npm i
      - name: Lint
        run: npm run lint